apiVersion: v1
kind: Secret
metadata:
  name: loginfailedattempt-secret
type: Opaque
stringData:
  security.protocol: SASL_SSL
  ssl.truststore.location: <Trustore location>
  ssl.truststore.password: <Trustore password>
  sasl.mechanism: OAUTHBEARER
  sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username="mike" password="mike" metadataServerUrls="http://localhost:8090";
  sasl.login.callback.handler.class: io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler